apiVersion: apps/v1
kind: Deployment
metadata:
  name: iop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iop
  template:
    metadata:
      labels:
        app: iop
    spec:
      containers:
      - image: okteto.dev/iop:latest
        name: iop
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "ce5614fd-a38c-4a05-9304-2bede0f20d8c"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "ce5614fd-a38c-4a05-9304-2bede0f20d8c"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
